"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronDown, Database, Eye, EyeOff, ListPlus, Plus, Search, Tag } from "lucide-react";
import { auth } from "@/lib/firebase";
import { isAdmin } from "@/lib/utils";
import type { ExamId, SkillId } from "@/lib/prep/types";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type PracticeRecord = { docId:string; sourceId:string; exam:ExamId; skill:SkillId; source:"static"|"custom"; isPublished:boolean; title:string; practiceType:string; part:string|number; difficulty:string; itemCount:number; updatedAt:string|null };
const exams: { id: "all"|ExamId; label:string }[] = [{id:"all",label:"All Practice"},{id:"toefl",label:"TOEFL"},{id:"ielts",label:"IELTS"},{id:"toeic",label:"TOEIC"}];
const skillLabel: Record<SkillId,string> = {reading:"Reading",listening:"Listening",speaking:"Speaking",writing:"Writing"};
function classify(s:PracticeRecord){const value=String(s.part||s.practiceType||"Other");const isPart=/^(part|task)-?\d+/i.test(value)||(s.exam==="toeic"&&/^part-/i.test(s.practiceType));return {kind:isPart?"Part":"Type",value};}
function pretty(value:string){return value.split("-").map(v=>v?`${v[0].toUpperCase()}${v.slice(1)}`:v).join(" ")}

function template(exam:ExamId,skill:SkillId) {
  const c={id:`${exam}-${skill}-${Date.now()}`,exam,skill,title:"New Practice Set",description:"",difficulty:"medium",practiceType:""};
  if(skill==="reading") return {...c,timeLimitSec:1200,passageTitle:"Passage title",paragraphs:[{label:"A",text:"Passage text"}],questions:[]};
  if(skill==="listening") return {...c,timeLimitSec:600,transcript:"Transcript",playLimitInTest:1,questions:[]};
  if(skill==="speaking") return {...c,tasks:[]};
  return {...c,practiceType:exam==="toefl"?"academic-discussion":"task-2",rubric:exam==="toefl"?"toefl-academic-discussion":"ielts-task2",timeLimitSec:600,promptText:"Writing prompt"};
}

export default function PracticePage(){
  const router=useRouter(); const [sets,setSets]=useState<PracticeRecord[]>([]); const [loading,setLoading]=useState(true); const [exam,setExam]=useState<"all"|ExamId>("all"); const [skill,setSkill]=useState<"all"|SkillId>("all"); const [query,setQuery]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [collapsed,setCollapsed]=useState<Set<string>>(()=>new Set()); const [create,setCreate]=useState(false); const [newExam,setNewExam]=useState<ExamId>("toefl"); const [newSkill,setNewSkill]=useState<SkillId>("reading"); const [json,setJson]=useState("");
  const call=useCallback(async(url:string,init?:RequestInit)=>{if(!auth.currentUser)throw new Error("認証が必要です。");const token=await auth.currentUser.getIdToken();const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...init?.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"処理に失敗しました。");return d},[]);
  const load=useCallback(async()=>setSets((await call("/api/admin/practice-sets")).practiceSets),[call]);
  useEffect(()=>auth.onAuthStateChanged(async u=>{if(!u)return router.replace("/login");if(!isAdmin(u.email))return router.replace("/");try{await load()}catch(e){alert(e instanceof Error?e.message:"読込失敗")}finally{setLoading(false)}}),[load,router]);
  const filtered=useMemo(()=>sets.filter(s=>(exam==="all"||s.exam===exam)&&(skill==="all"||s.skill===skill)&&(!query||`${s.title} ${s.sourceId} ${s.practiceType}`.toLowerCase().includes(query.toLowerCase()))),[sets,exam,skill,query]);
  const groups=useMemo(()=>Object.entries(skillLabel).map(([id,label])=>{const skillSets=filtered.filter(s=>s.skill===id);const map=new Map<string,{kind:string;value:string;sets:PracticeRecord[]}>();for(const s of skillSets){const c=classify(s),key=`${c.kind}:${c.value}`;const group=map.get(key)||{...c,sets:[]};group.sets.push(s);map.set(key,group)}return{id:id as SkillId,label,sections:[...map.values()].sort((a,b)=>`${a.kind}-${a.value}`.localeCompare(`${b.kind}-${b.value}`))}}).filter(g=>g.sections.length),[filtered]);
  const counts=useMemo(()=>new Map(exams.map(e=>[e.id,e.id==="all"?sets.length:sets.filter(s=>s.exam===e.id).length])),[sets]);
  async function toggle(s:PracticeRecord){try{setBusy(s.docId);await call(`/api/admin/practice-sets/${s.docId}`,{method:"PATCH",body:JSON.stringify({sourceId:s.sourceId,exam:s.exam,skill:s.skill,source:s.source,isPublished:!s.isPublished})});await load()}catch(e){alert(e instanceof Error?e.message:"更新失敗")}finally{setBusy(null)}}
  function toggleGroup(key:string){setCollapsed(prev=>{const next=new Set(prev);next.has(key)?next.delete(key):next.add(key);return next})}
  function openCreate(){setNewExam("toefl");setNewSkill("reading");setJson(JSON.stringify(template("toefl","reading"),null,2));setCreate(true)}
  function changeTemplate(e:ExamId,s:SkillId){setNewExam(e);setNewSkill(s);setJson(JSON.stringify(template(e,s),null,2))}
  async function save(){try{setBusy("create");const data=JSON.parse(json);data.exam=newExam;data.skill=newSkill;await call("/api/admin/practice-sets",{method:"POST",body:JSON.stringify({data,isPublished:false})});setCreate(false);await load()}catch(e){alert(e instanceof Error?e.message:"保存失敗")}finally{setBusy(null)}}
  if(loading)return <div className="grid min-h-screen place-items-center">Loading...</div>;
  return <div className="flex h-screen flex-col overflow-hidden">
    <header className="flex items-center justify-between border-b bg-white px-6 py-5 dark:border-slate-700 dark:bg-slate-900"><div><h1 className="text-2xl font-bold">Practice</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">試験・技能ごとにTypeまたはPartで演習を管理します。</p></div><Button onClick={openCreate}><Plus className="h-4 w-4"/>Create Practice</Button></header>
    <div className="flex min-h-0 flex-1">
      <aside className="w-56 shrink-0 overflow-y-auto border-r bg-white p-3 dark:border-slate-700 dark:bg-slate-900"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Exam</p>{exams.map(e=><button key={e.id} onClick={()=>setExam(e.id)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm ${exam===e.id?"bg-blue-50 font-medium text-blue-700 dark:bg-blue-950 dark:text-blue-300":"text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><Tag className="h-4 w-4"/><span className="flex-1 text-left">{e.label}</span><span className="text-xs text-slate-400">{counts.get(e.id)}</span></button>)}<p className="mt-5 px-3 py-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Skill</p>{([{id:"all",label:"All Skills"},...Object.entries(skillLabel).map(([id,label])=>({id,label}))] as {id:"all"|SkillId;label:string}[]).map(s=><button key={s.id} onClick={()=>setSkill(s.id)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm ${skill===s.id?"bg-blue-50 font-medium text-blue-700 dark:bg-blue-950 dark:text-blue-300":"text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800"}`}><Database className="h-4 w-4"/>{s.label}</button>)}</aside>
      <main className="min-w-0 flex-1 overflow-auto p-6"><div className="mb-5 flex items-center justify-between"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input className="w-72 pl-9" placeholder="Search practice..." value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="text-sm text-slate-500">{filtered.length} sets</p></div>
        <div className="space-y-8">{groups.map(g=><section key={g.id}><div className="mb-3 flex items-center gap-2"><Database className="h-5 w-5 text-slate-500"/><h2 className="text-lg font-bold">{g.label}</h2><Badge variant="secondary">{g.sections.reduce((n,s)=>n+s.sets.length,0)}</Badge></div><div className="space-y-4">{g.sections.map(section=>{const groupKey=`${g.id}-${section.kind}-${section.value}`;const isCollapsed=collapsed.has(groupKey);return <div key={groupKey} className="overflow-hidden rounded-xl border bg-white dark:border-slate-700 dark:bg-slate-900"><div role="button" tabIndex={0} onClick={()=>toggleGroup(groupKey)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")toggleGroup(groupKey)}} className="flex cursor-pointer items-center gap-3 border-b px-4 py-3 transition hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><ChevronDown className={`h-4 w-4 transition-transform ${isCollapsed?"-rotate-90":""}`}/><Badge variant="outline">{section.kind}</Badge><h3 className="font-semibold">{pretty(section.value)}</h3><span className="text-xs text-slate-400">{section.sets.length} sets</span>{(["reading","listening"] as SkillId[]).includes(g.id)&&<Button className="ml-auto" variant="outline" size="sm" onClick={e=>{e.stopPropagation();router.push(`/admin/practice-sets/bulk/${section.sets[0].exam}/${g.id}/${section.kind.toLowerCase()}/${encodeURIComponent(section.value)}`)}}><ListPlus className="h-4 w-4"/>Bulk</Button>}</div>{!isCollapsed&&<table className="w-full text-sm"><thead><tr className="border-b bg-slate-50/70 text-left text-slate-500 dark:border-slate-700 dark:bg-slate-800/70 dark:text-slate-400"><th className="px-4 py-3">Title</th><th className="px-4 py-3">Questions</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{section.sets.map(s=><tr key={s.docId} onClick={()=>router.push(`/admin/practice-sets/${s.docId}`)} className="cursor-pointer border-b last:border-0 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><td className="px-4 py-3"><p className="font-medium">{s.title}</p><p className="text-xs text-slate-400">{s.sourceId}</p></td><td className="px-4 py-3">{s.itemCount}</td><td className="px-4 py-3"><Badge variant="outline">{s.source==="static"?"JSON":"Firestore"}</Badge></td><td className="px-4 py-3"><Badge className={s.isPublished?"bg-green-100 text-green-700":"bg-slate-100 text-slate-600"}>{s.isPublished?"Published":"Draft"}</Badge></td><td className="px-4 py-3 text-right"><Button variant="outline" size="sm" disabled={busy===s.docId} onClick={e=>{e.stopPropagation();toggle(s)}}>{s.isPublished?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</Button></td></tr>)}</tbody></table>}</div>})}</div></section>)}{!groups.length&&<div className="rounded-xl border border-dashed py-20 text-center text-slate-500">No practice sets</div>}</div>
      </main>
    </div>
    <Dialog open={create} onOpenChange={setCreate}><DialogContent className="max-h-[90vh] max-w-3xl overflow-auto"><DialogHeader><DialogTitle>Create Practice</DialogTitle><DialogDescription>試験・技能を選び、JSONテンプレートを編集して作成します。</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-4"><div><Label>Exam</Label><select className="mt-2 h-9 w-full rounded-md border px-3" value={newExam} onChange={e=>changeTemplate(e.target.value as ExamId,newSkill)}><option value="toefl">TOEFL</option><option value="ielts">IELTS</option><option value="toeic">TOEIC</option></select></div><div><Label>Skill</Label><select className="mt-2 h-9 w-full rounded-md border px-3" value={newSkill} onChange={e=>changeTemplate(newExam,e.target.value as SkillId)}><option value="reading">Reading</option><option value="listening">Listening</option><option value="speaking">Speaking</option><option value="writing">Writing</option></select></div></div><Textarea className="min-h-[430px] font-mono text-xs" value={json} onChange={e=>setJson(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setCreate(false)}>Cancel</Button><Button disabled={busy==="create"} onClick={save}>Create Draft</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
