"use client";

import { useMemo, useRef, useState } from "react";
import { Bold, ImagePlus, Italic, Loader2, Trash2, UploadCloud } from "lucide-react";
import { deleteObject, getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { storage } from "@/lib/firebase";
import MarkdownLite from "@/components/prep/MarkdownLite";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Props={value:string;onChange:(value:string)=>void;storagePrefix:string;height?:number;emptyPreview?:string};
const imagePattern=/!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g;

export function AdminMarkdownSplitEditor({value,onChange,storagePrefix,height=500,emptyPreview="No content"}:Props){const textarea=useRef<HTMLTextAreaElement>(null);const input=useRef<HTMLInputElement>(null);const selection=useRef({start:value.length,end:value.length});const [uploading,setUploading]=useState(false);const [drag,setDrag]=useState(false);const images=useMemo(()=>[...value.matchAll(imagePattern)].map(m=>({markdown:m[0],alt:m[1],url:m[2]})),[value]);
function remember(){if(textarea.current)selection.current={start:textarea.current.selectionStart,end:textarea.current.selectionEnd}}
function insert(markdown:string){const {start,end}=selection.current;const before=value.slice(0,start),after=value.slice(end),padBefore=before&&!before.endsWith("\n")?"\n\n":"",padAfter=after&&!after.startsWith("\n")?"\n\n":"";const next=`${before}${padBefore}${markdown}${padAfter}${after}`;onChange(next);requestAnimationFrame(()=>{const pos=(before+padBefore+markdown).length;textarea.current?.focus();textarea.current?.setSelectionRange(pos,pos)})}
function wrap(mark:string){const {start,end}=selection.current;const selected=value.slice(start,end)||"text";const next=`${value.slice(0,start)}${mark}${selected}${mark}${value.slice(end)}`;onChange(next)}
async function upload(files:FileList|File[]){const list=Array.from(files);if(list.length!==1)return alert("画像は1ファイルずつアップロードしてください。");const file=list[0];if(!file.type.startsWith("image/"))return alert("画像ファイルのみ対応しています。");try{setUploading(true);const path=`${storagePrefix}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const url=await getDownloadURL((await uploadBytes(ref(storage,path),file)).ref);insert(`![Uploaded image](${url})`)}catch(e){alert(e instanceof Error?e.message:"画像アップロードに失敗しました。")}finally{setUploading(false);if(input.current)input.current.value=""}}
async function remove(image:{markdown:string;url:string}){if(!confirm("Storageから画像を削除し、Markdownからも取り除きますか？"))return;try{await deleteObject(ref(storage,image.url));onChange(value.replace(image.markdown,"").replace(/\n{3,}/g,"\n\n").trim())}catch(e){alert(e instanceof Error?e.message:"画像削除に失敗しました。")}}
return <div className="space-y-4"><div className="grid overflow-hidden border-y md:grid-cols-2 dark:border-slate-800" style={{height}}><div className={`flex min-h-0 flex-col border-r transition dark:border-slate-800 ${drag?"bg-blue-50 dark:bg-blue-950/20":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={e=>{e.preventDefault();setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files)}}><div className="flex h-14 shrink-0 items-center gap-2 border-b px-4 dark:border-slate-800"><span className="mr-auto flex items-center gap-2 font-semibold">Markdownエディタ <span className="hidden text-xs font-normal text-slate-400 xl:inline"><UploadCloud className="inline h-3 w-3"/> Drop image</span></span><Button type="button" variant="ghost" size="icon" onClick={()=>wrap("**")}><Bold className="h-4 w-4"/></Button><Button type="button" variant="ghost" size="icon" onClick={()=>wrap("*")}><Italic className="h-4 w-4"/></Button><input ref={input} type="file" accept="image/*" className="hidden" onChange={e=>e.target.files&&upload(e.target.files)}/><Button type="button" variant="outline" size="sm" disabled={uploading} onClick={()=>{remember();input.current?.click()}}>{uploading?<Loader2 className="h-4 w-4 animate-spin"/>:<ImagePlus className="h-4 w-4"/>}Upload image</Button></div><Textarea ref={textarea} data-guide-markdown-editor value={value} onChange={e=>{onChange(e.target.value);remember()}} onClick={remember} onKeyUp={remember} onSelect={remember} className="min-h-0 flex-1 resize-none rounded-none border-0 p-5 font-mono leading-7 focus-visible:ring-0"/></div><div className="flex min-h-0 flex-col"><div className="flex h-14 shrink-0 items-center border-b px-5 font-semibold dark:border-slate-800">Preview</div><div className="min-h-0 flex-1 overflow-auto p-6 leading-7"><MarkdownLite text={value||emptyPreview}/></div></div></div>{images.length>0&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Uploaded Images</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{images.map((image,i)=><div key={`${image.url}-${i}`} className="rounded-lg border p-3 dark:border-slate-700"><img src={image.url} alt={image.alt||"Uploaded"} className="h-36 w-full rounded object-cover"/><p className="mt-2 truncate text-xs text-slate-500">{image.alt||`Image ${i+1}`}</p><Button type="button" variant="destructive" size="sm" className="mt-2" onClick={()=>remove(image)}><Trash2 className="h-4 w-4"/>Delete image</Button></div>)}</div></div>}</div>}
