"use client";

import { useCallback, useEffect, useMemo, useState } from "react"; import { useParams,useRouter } from "next/navigation"; import { ArrowLeft, ClipboardPaste, Upload } from "lucide-react"; import { auth } from "@/lib/firebase"; import { parseFormattedPracticeText } from "@/lib/prep/formatted-import"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Textarea } from "@/components/ui/textarea"; import { Badge } from "@/components/ui/badge";

export default function BulkPage(){const {docId}=useParams<{docId:string}>();const router=useRouter();const [record,setRecord]=useState<any>(null);const [text,setText]=useState("");const [busy,setBusy]=useState(false);
const call=useCallback(async(url:string,init?:RequestInit)=>{if(!auth.currentUser)throw new Error("認証が必要です。");const token=await auth.currentUser.getIdToken();const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...init?.headers}});const d=await r.json();if(!r.ok)throw new Error(d.error||"処理に失敗しました。");return d},[]);useEffect(()=>{call(`/api/admin/practice-sets/${docId}`).then(setRecord).catch(e=>alert(e.message))},[call,docId]);
const blocks=useMemo(()=>{try{return parseFormattedPracticeText(text)}catch{return[]}},[text]);const count=blocks.reduce((n,b)=>n+b.questions.length,0);
async function importAll(){try{if(!record?.data||!count)throw new Error("Importできる問題がありません。");if(!["reading","listening"].includes(record.data.skill))throw new Error("Bulk CreateはReading / Listeningに対応しています。");setBusy(true);const current=Array.isArray(record.data.questions)?record.data.questions:[];const added=blocks.flatMap(b=>b.questions);const data={...record.data,questions:[...current,...added].map((q:any,i:number)=>({...q,number:i+1}))};await call(`/api/admin/practice-sets/${docId}`,{method:"PUT",body:JSON.stringify({data,isPublished:record.isPublished,source:record.source})});router.push(`/admin/practice-sets/${docId}`)}catch(e){alert(e instanceof Error?e.message:"Import失敗")}finally{setBusy(false)}}
return <main className="p-5 md:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="flex items-center gap-4"><Button variant="ghost" onClick={()=>router.push(`/admin/practice-sets/${docId}`)}><ArrowLeft className="h-4 w-4"/>Back</Button><div><h1 className="text-2xl font-bold">Bulk Create</h1><p className="text-sm text-slate-500">{record?.data?.title||"Loading..."}</p></div></header><Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><ClipboardPaste className="h-5 w-5"/>Paste formatted text</CardTitle><div className="flex gap-2"><Badge variant="outline">{blocks.length} articles</Badge><Badge variant="outline">{count} questions</Badge></div></div></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-600">ARTICLE / ARTICLE_JA / TAGS / QUESTION_TYPE / QUESTION / A〜D / ANSWER / EXPLANATION 形式をまとめて貼り付けてください。</p><Textarea className="min-h-[520px] font-mono text-xs" value={text} onChange={e=>setText(e.target.value)} placeholder="ARTICLE:\n...\nQUESTION_TYPE: mcq\nQUESTION:\n...\nA: ...\nB: ...\nC: ...\nD: ...\nANSWER: A\nEXPLANATION:\n..."/><div className="flex justify-end"><Button disabled={busy||!count} onClick={importAll}><Upload className="h-4 w-4"/>{busy?"Importing...":`Import ${count} questions`}</Button></div></CardContent></Card></div></main>}
