"use client";

import { useCallback, useMemo, useState } from "react"; import { useParams,useRouter } from "next/navigation"; import { ArrowLeft, Upload } from "lucide-react"; import { auth } from "@/lib/firebase"; import { parseFormattedPracticeText } from "@/lib/prep/formatted-import"; import type { ExamId,SkillId } from "@/lib/prep/types"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea"; import { Badge } from "@/components/ui/badge";

function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,45)||"set"}
export default function GroupBulk(){const p=useParams<{exam:ExamId;skill:SkillId;kind:string;value:string}>();const router=useRouter();const value=decodeURIComponent(p.value);const [text,setText]=useState("");const [prefix,setPrefix]=useState(value.split("-").map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" "));const [busy,setBusy]=useState(false);const blocks=useMemo(()=>parseFormattedPracticeText(text),[text]);const questions=blocks.reduce((n,b)=>n+b.questions.length,0);
const call=useCallback(async(url:string,init?:RequestInit)=>{if(!auth.currentUser)throw new Error("認証が必要です。");const token=await auth.currentUser.getIdToken();const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...init?.headers}});const d=await r.json();if(!r.ok)throw new Error(d.error||"処理に失敗しました。");return d},[]);
async function createAll(){try{if(!blocks.length)throw new Error("ARTICLEブロックを解析できませんでした。");setBusy(true);for(let i=0;i<blocks.length;i++){const b=blocks[i],id=`${p.exam}-${p.skill}-${slug(value)}-${Date.now()}-${i+1}`;const common:any={id,exam:p.exam,skill:p.skill,title:`${prefix} ${i+1}`,description:"",difficulty:"medium",practiceType:value,timeLimitSec:p.skill==="reading"?1200:600,questions:b.questions};if(p.kind==="part")common.part=value;if(p.skill==="reading"){common.passageTitle=`${prefix} ${i+1}`;common.paragraphs=[{label:"A",text:b.article}];if(b.articleJa)common.translationJa=b.articleJa}else{common.transcript=b.article;common.transcriptJa=b.articleJa||undefined;common.playLimitInTest=1}await call("/api/admin/practice-sets",{method:"POST",body:JSON.stringify({data:common,isPublished:false})})}router.push("/admin/practice-sets")}catch(e){alert(e instanceof Error?e.message:"Bulk作成に失敗しました。")}finally{setBusy(false)}}
return <main className="p-5 md:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="flex items-center gap-4"><Button variant="ghost" onClick={()=>router.push("/admin/practice-sets")}><ArrowLeft className="h-4 w-4"/>Back</Button><div><h1 className="text-2xl font-bold">Bulk Create</h1><div className="mt-2 flex gap-2"><Badge>{p.exam.toUpperCase()}</Badge><Badge variant="outline">{p.skill}</Badge><Badge variant="outline">{p.kind}: {value}</Badge></div></div></header><Card><CardHeader><CardTitle>複数の演習セットを一括作成</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Title prefix</Label><Input className="mt-2" value={prefix} onChange={e=>setPrefix(e.target.value)}/></div><p className="text-sm text-slate-500">ARTICLEブロック1つにつき、1つのDraft演習セットを作成します。</p><Textarea className="min-h-[520px] font-mono text-xs" value={text} onChange={e=>setText(e.target.value)} placeholder="ARTICLE:\n...\nQUESTION_TYPE: mcq\nQUESTION:\n...\nA: ...\nB: ...\nC: ...\nD: ...\nANSWER: A\nEXPLANATION:\n..."/><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{blocks.length} sets / {questions} questions</p><Button disabled={busy||!blocks.length} onClick={createAll}><Upload className="h-4 w-4"/>{busy?"Creating...":`Create ${blocks.length} drafts`}</Button></div></CardContent></Card></div></main>}
